"""empty message

Revision ID: 306a4469c780
Revises: fccd33ba1e9b
Create Date: 2020-01-27 14:59:08.521318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306a4469c780'
down_revision = 'fccd33ba1e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
