"""empty message

Revision ID: b83d35a03151
Revises: e9cc1c2cab3b
Create Date: 2020-01-23 15:35:16.874772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b83d35a03151'
down_revision = 'e9cc1c2cab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('post', sa.String(length=1000), nullable=False))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('post', 'title')
    op.drop_column('post', 'image')
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('post', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('post', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'post')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
