"""empty message

Revision ID: ffdefe8dc6f9
Revises: 306a4469c780
Create Date: 2020-01-27 15:44:10.646418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffdefe8dc6f9'
down_revision = '306a4469c780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('birthday', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('profile', sa.Column('occupation', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('skills', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'users', ['user_id'], ['id'])
    op.drop_column('profile', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('nickname', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    op.drop_column('profile', 'updated_at')
    op.drop_column('profile', 'skills')
    op.drop_column('profile', 'occupation')
    op.drop_column('profile', 'created_at')
    op.drop_column('profile', 'birthday')
    op.drop_column('profile', 'address')
    # ### end Alembic commands ###
